### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [cyber470/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Tudo ok com a implementação. So faltou um detalhe: os itens do nav deveriam estar presentes em todas as páginas e listagem da cor das tarefas deveria alternar conforme o status. 

https://github.com/cyber470/0.5.1/blob/516bb4672114b9dc70c41650aa7e1e27ca8f3c83/index.html#L14-L18

Para o primeiro ítem, bastaria adicionar os botões em cada arquivo `.html`. Para o segundo ítem, bastaria aplicar um estilo de cor diferente para as listagem para status diferentes do "pendentes" ─ Isso pode ser aplicado através do uso de uma _class_. 

```html
<div class="box">
  <p class="excluida">Minha tarefas</p>
</div>
```

**Nota:** 5 

# Comentários

Notei que muitas das suas propriedades CSS são duplicadas entre as classes `pendentes` `concluidas` e `excluidas`. Você poderia criar uma classe mais genérica para armazenar essas propriedades e então fazer uso de duas classes. Veja no exemplo abaixo que é utilizada a classe `tarefa` junto com a classe `pendentes`. 

```html
<a class="tarefa pendentes" href="/pendentes.html">Pendentes</a>
``` 

O CSS ficaria assim: 

```css
.tarefa {
    font-family: sans-serif;
    color: rgb(250, 250, 250);
    font-size: 14px;
    border-style: solid;
    text-align: center;
    border-collapse: collapse;
    border-radius: 15px;
    padding: 11px;
    text-decoration: none;
    border: #0ca789;
    margin: 8px; 
    font-weight: bold; 
}

.pendentes {
    background: #8fd14f;
}

.concluidas {
    background: #0ca789;
    
}

.excluidas {
    background: #eb4045;
}
```

Você pode imaginar agora que `tarefa` possui três subvariações: `pendentes`, `concluidas` e `excluidas`.

```mermaid
flowchart LR;
  tarefa --> concluida;
  tarefa --> pendente;
  tarefa --> excluida;
```

Notei, também, que o seu código está muito mal indentado (especialmente o CSS). No VS Code você pode aplicar a formação automaticamente seguindo esses passos:
1. CTRL + P para abrir o executor de comandos
2. Digite "> Format Document"
